# Generated by Django 4.1.4 on 2022-12-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_contact_us'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_us',
        ),
    ]
